name = "wedding-photo-frontend" # IMPORTANTE: Deve corrispondere al nome del tuo progetto su Cloudflare Pages
pages_build_output_dir = "./dist"
compatibility_date = "2025-06-03" # Usa una data recente, come quella del log o odierna
